[versions]
jvm = "2.2.20"
ktor = "3.1.2"
reactor_core = "3.7.6"
coroutines_reactor = "1.10.2"
testcontainers = "1.20.6"
mockk = "1.13.17"
exposed = "0.57.0"
postgresql = "42.7.4"
hikaricp = "6.1.0"
flyway = "11.2.0"
junit = "5.11.4"

[libraries]
ktor_server_core_jvm = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor_server_netty_jvm = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
ktor_server_host_common_jvm = { group = "io.ktor", name = "ktor-server-host-common-jvm", version.ref = "ktor" }
ktor_server_test_host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
ktor_serialization_kotlinx_json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor_server_content_negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor_server_status_pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor_client_okhttp = { group = "io.ktor", name = "ktor-client-okhttp-jvm", version.ref = "ktor" }
ktor_client_core = { group = "io.ktor", name = "ktor-client-core-jvm", version.ref = "ktor" }
ktor_client_content_negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
reactor_core = { group = "io.projectreactor", name = "reactor-core", version.ref = "reactor_core" }
kotlinx_coroutines_reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "coroutines_reactor" }
kotlinx_coroutines_test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test-jvm", version.ref = "coroutines_reactor" }
reactor_test = { group = "io.projectreactor", name = "reactor-test", version.ref = "reactor_core" }
testcontainer_kafka = { group = "org.testcontainers", name = "kafka", version.ref = "testcontainers" }
testcontainer_postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
exposed_core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed_dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }
exposed_jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
flyway_core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway_postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
junit_jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit_jupiter_api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit_jupiter_engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

[bundles]
common = [
    "reactor_core",
    "kotlinx_coroutines_reactor",
]
ktor-server = [
    "ktor_server_core_jvm",
    "ktor_server_netty_jvm",
    "ktor_server_host_common_jvm",
    "ktor_serialization_kotlinx_json",
    "ktor_server_content_negotiation",
    "ktor_server_status_pages",
]
ktor-client = [
    "ktor_client_core",
    "ktor_client_okhttp",
    "ktor_client_content_negotiation",
]
ktor-test = [
    "reactor_test",
    "kotlinx_coroutines_test",
    "ktor_server_test_host",
    "testcontainer_kafka",
    "testcontainer_postgresql",
    "mockk",
    "junit_jupiter",
    "junit_jupiter_api",
    "junit_jupiter_engine"
]
database = [
    "exposed_core",
    "exposed_dao", 
    "exposed_jdbc",
    "postgresql",
    "hikaricp",
    "flyway_core",
    "flyway_postgresql",
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jvm" }
